### ISSUE TITLE
sms-mt bypass, $passphrase?

### ISSUE THREAD

**Issue by janinecriselle** [glabsdev/php#2]
Hi, how to identify or create the value for parameter "passphrase"? Thank you.

**Comment by van0219** [comment]
Oo nga, wala din yan sa documentation.

**Comment by joyfementira** [comment]
I think yan yung sender address or just leave it unique numbers.

**Comment by janinecriselle** [comment]
It's like a password; alpa-numeric. It's used to bypass the opt-in flow.

**Comment by janinecriselle** [comment]
> 
> 
> I think yan yung sender address or just leave it unique numbers.

Tried using random string, still not working.

**Comment by ghost** [comment]
oo pano malaman yung passphrase?

**Comment by janinecriselle** [comment]
GlobeLabs will provide the passphrase. Contact them via their e-mail (api@globe.com.ph), they’ll give you the process.

**Comment by joyfementira** [comment]
To bypass the consent workflow, they would be requiring us to fill-out the SD Form and User Flow Form. After approval, they'll provide you the passphrase you need.

**Comment by rondelserrano** [comment]
I am currently working on a project that includes this "passphrase" with glabs. Sila actually yung mag po provide non once mag karon kayo ng agreement to bypass the access_token. So makukuha mo lang sya kapag may done deal kana with glabs. :) hope it helps.
